name: Build Status

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false  # Ensure one failure doesn't cancel other jobs
      matrix:
        target: [standard_gcy, standard_hjy, standard_wwj, standard_yx]

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t dev-env -f .devcontainer/Dockerfile .

    - name: Configure CMake
      run: |
        docker run --rm --user root -v ${{ github.workspace }}:/workspaces/Vision-Final-Test -w /workspaces/Vision-Final-Test dev-env /bin/bash -c "source /opt/ros/humble/setup.bash && source /opt/intel/openvino_2024/setupvars.sh && cmake -B build -DCMAKE_BUILD_TYPE=Release"

    - name: Build Target
      run: |
        docker run --rm --user root -v ${{ github.workspace }}:/workspaces/Vision-Final-Test -w /workspaces/Vision-Final-Test dev-env /bin/bash -c "source /opt/ros/humble/setup.bash && source /opt/intel/openvino_2024/setupvars.sh && cmake --build build --target ${{ matrix.target }} --parallel"
